### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by zachthedev** [amiad/node-soundcloud2podcast#1]
The output RSS from this script is no compatible with Spotify Podcasts RSS feed. It thinks that the author and email address is missing.
Comparing this output to the SoundCloud one (the one you get from your profile) is formatted right, while this one is slightly different and causes issues. I can't seem to figure out what is wrong.

[My ouput](https://gist.githubusercontent.com/Zangoran/29c2763c7a5e6b257893a0ec77a8d430/raw/642e78bb538f2fa84997a49ba6aa4d2861f382b2/bbm.rss)
[Soundcloud RSS (just one profile)](http://feeds.soundcloud.com/users/soundcloud:users:149227732/sounds.rss)

**Comment by amiad** [comment]
I can add `itunes:name` tag but I can't add `itunes:email`. I not get it from SoundCloud.

**Comment by zachthedev** [comment]
I added both of them manually, but spotify still doesn't recognize it. Something is different between soundcloud rss feed and the feed you created

**Comment by amiad** [comment]
I don't know what the problem. But if you have offical RSS then why you need RSS from soundcloud2podcast and to send it to spotify?
